import { Activity, ProfileDetails, ProfileRow } from './types';

export const mockProfileDetails: ProfileDetails = {
    profileSrc: 'https://github.com/nborzunov',
    photoSrc: 'https://picsum.photos/200/300',
    fullName: 'Nikolay Borzunov',
    location: 'Armenia, Yerevan',
    languages: ['JavaScript', 'TypeScript', 'Rust', 'Python'],
    activity: Activity.High,
    commits: 150,
    repositories: [],
    linkedin: 'https://www.linkedin.com/in/nikolay-borzunov-5b5b3b1b3/',
    readme: '',
};

export const mockProfiles: ProfileRow[] = [
    {
        profileSrc: 'https://github.com/nborzunov',
        photoSrc: 'https://picsum.photos/200/300',
        fullName: 'Nikolay Borzunov',
        location: 'Armenia, Yerevan',
        languages: ['JavaScript', 'TypeScript', 'Rust', 'Python'],
        activity: Activity.High,
        commits: 150,
        createdAt: '2021-03-01T12:00:00.000Z',
        followers: 1500,
    },
    {
        profileSrc: 'https://github.com/nborzunov',
        photoSrc: 'https://picsum.photos/200/300',
        fullName: 'Nikolay Borzunov',
        location: 'Armenia, Yerevan',
        languages: ['JavaScript', 'TypeScript', 'Rust', 'Python'],
        activity: Activity.Medium,
        commits: 150,
        createdAt: '2021-03-01T12:00:00.000Z',
        followers: 1500,
    },
    {
        profileSrc: 'https://github.com/nborzunov',
        photoSrc: 'https://picsum.photos/200/300',
        fullName: 'Nikolay Borzunov',
        location: 'Armenia, Yerevan',
        languages: ['JavaScript', 'TypeScript', 'Rust', 'Python'],
        activity: Activity.Low,
        commits: 150,
        createdAt: '2021-03-01T12:00:00.000Z',
        followers: 1500,
    },
    {
        profileSrc: 'https://github.com/nborzunov',
        photoSrc: 'https://picsum.photos/200/300',
        fullName: 'Nikolay Borzunov',
        location: 'Armenia, Yerevan',
        languages: ['JavaScript', 'TypeScript', 'Rust', 'Python'],
        activity: Activity.High,
        commits: 150,
        createdAt: '2021-03-01T12:00:00.000Z',
        followers: 1500,
    },
    {
        profileSrc: 'https://github.com/nborzunov',
        photoSrc: 'https://picsum.photos/200/300',
        fullName: 'Nikolay Borzunov',
        location: 'Armenia, Yerevan',
        languages: ['JavaScript', 'TypeScript', 'Rust', 'Python'],
        activity: Activity.High,
        commits: 150,
        createdAt: '2021-03-01T12:00:00.000Z',
        followers: 1500,
    },
];
